version: '3.8'

services:
  projeto-teste:
    container_name: projeto-teste
    image: postgres:16.0
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: teste_db
    ports:
      - "5437:5432"
    volumes:
    - ./src/sql:/docker-entrypoint-initdb.d