version: '3.8'

services:
  projeto-ptax:
    container_name: postgres-database
    image: postgres:16.0
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: teste_db
    ports:
      - "5437:5432"
    volumes:
    - ./src/sql:/docker-entrypoint-initdb.d